changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot
      - github-actions

  categories:
    - title: "⚠️ Breaking Changes"
      labels: [breaking]

    - title: "New Features"
      labels: [feature, enhancement]

    - title: "New Language Features"
      labels: [vertex, edge, flair, vsave, dsl]

    - title: "Runtime Changes"
      labels: [vm, ecs, runtime, performance]

    - title: "Bindings Changes"
      labels: [godot, bevy, binding]

    - title: "Bug Fixes"
      labels: [bug, fix]

    - title: "Documentation Updates"
      labels: [docs, documentation]

    - title: "Maintenance"
      labels: [chore, ci, refactor, internal]

    - title: "Dependencies"
      labels: [dependencies]

    - title: "Other Changes"
      labels: ["*"]