name: Build

on:
  workflow_call:
    outputs:
      artifact:
        description: Name of the uploaded artifact
        value: ${{ jobs.build.outputs.artifact }}

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      artifact: ${{ steps.build.outputs.artifact }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          submodules: true

      - name: setup-shellops
        run: source shell/actions/setup-ops

      - uses: actions/setup-go@v5
        with:
          go-version-file: go/go.mod

      - name: setup-rust
        run: shell/actions/setup-rust

      - name: build-and-package
        id: build
        run: |
          echo "artifact=$(./shell/scripts/chores/build.sh --release --bundle)" \
            >> "$GITHUB_OUTPUT"

      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.artifact }}
          path: ${{ steps.build.outputs.artifact }}.tar.gz
