name: Lint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: setup-shellops
        run: source shell/actions/setup-ops

      - uses: actions/setup-go@v5
        with:
          go-version-file: go/go.mod

      - name: setup-rust
        run: |
          rustup toolchain install stable --profile minimal --component rustfmt
          rustup default stable

      - name: check-formatting
        run: ./shell/scripts/chores/lint.sh
