name: Security

on:
  workflow_call:

jobs:
  go:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: setup-shellops
        run: source shell/actions/setup-ops

      - uses: actions/setup-go@v5
        with:
          go-version-file: go/go.mod

      - name: install-tools
        run: shell/.ops/cli/install govulncheck

      - name: go-vulncheck
        run: cd go && govulncheck ./...

  rust:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: setup-shellops
        run: source shell/actions/setup-ops

      - name: setup-rust
        run: shell/actions/setup-rust

      - name: install-tools
        run: shell/.ops/cli/install cargo-binstall cargo-audit

      - name: rust-audit
        run: cargo audit -f crates/Cargo.lock
