name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - run: git fetch origin main

      - name: setup-shellops
        run: source shell/actions/setup-ops

      - uses: actions/setup-go@v5
        with:
          go-version-file: go/go.mod

      - name: setup-rust
        run: |
          rustup toolchain install stable --profile minimal
          rustup default stable

      - name: run-tests
        run: ./shell/scripts/ci/coverage.sh
