name: Run Tests and Upload Coverage

on:
  workflow_call:

jobs:
  coverage:
    name: test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive
      - run: git fetch origin main
      - uses: ./shell/.shock/actions/envrc
      - uses: ./.github/actions/setup

      - name: Install Coverage Tooling
        run: |
          ./shell/shock workspace \
            cargo-llvm-cov \
            gocover-cobertura

      - name: Run Tests
        run: ./shell/scripts/ci/coverage.sh

      - name: Upload Go Coverage
        if: hashFiles('./coverage/go_coverage.xml') != ''
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/go_coverage.xml
          flags: go
          fail_ci_if_error: true
          verbose: true

      - name: Upload Rust Coverage
        if: hashFiles('./coverage/rust_coverage.xml') != ''
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/rust_coverage.xml
          flags: rust
          fail_ci_if_error: true
          verbose: true