name: Create Release

on:
  workflow_call:

jobs:
  create_release:
    runs-on: ubuntu-24.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/envrc
      - run: ./scripts/chores/cicd_create_release.sh
