name: Create Release

on:
  workflow_call:
    outputs:
      tag:
        description: The release tag (e.g. v1.2.3-dev.4)
        value: ${{ jobs.release.outputs.tag }}

jobs:
  build:
    name: build
    uses: ./.github/workflows/_build.yaml
    secrets: inherit

  release:
    name: release
    runs-on: ubuntu-24.04
    needs: [build]
    permissions:
      contents: write
      actions: write
    outputs:
      tag: ${{ steps.publish.outputs.tag }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Generate Auth Token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.RELEASE_BOT_APP_ID }}
          private-key: ${{ secrets.RELEASE_BOT_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v6
        with:
          ref: main # make sure to get HEAD, instead of triggering commit
          token: ${{ steps.generate-token.outputs.token }}
          submodules: recursive

      - uses: ./shell/.shock/actions/envrc

      - name: Configure git
        uses: ./shell/.shock/actions/git-config

      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: ${{ needs.build.outputs.artifact }}

      - name: Create release
        id: publish
        run: |
          echo "tag=v$(jq -r '.latest' manifest.json)" >> "$GITHUB_OUTPUT"
          ./shell/scripts/ci/publish_release.sh \
            "${{ needs.build.outputs.artifact }}.tar.gz"

      - name: Update release index and deploy site
        run: |
          ./shell/scripts/ci/update_release_index.sh \
            "${{ needs.build.outputs.artifact }}.tar.gz"
