name: Deploy Docs Site

on:
  workflow_call:
    inputs:
      ref:
        description: >
          Git ref to build and deploy from.
          Defaults to the triggering ref.
        required: false
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref || github.ref }}

      - uses: actions/setup-node@v4
        with:
          node-version-file: ./.nvmrc

      - id: pnpm-version
        run: |
          pnpm_version=$(jq .packageManager < site/package.json | tr -d "\"" | cut -d'@' -f2)
          echo "version=$pnpm_version" >> "$GITHUB_OUTPUT"

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ steps.pnpm-version.outputs.version }}

      - name: Install Dependencies
        working-directory: ./site
        run: pnpm install

      - name: Build Static Site
        working-directory: ./site
        run: pnpm run build

      - uses: actions/upload-pages-artifact@v4
        with:
          path: ./site/dist

  deploy:
    name: deploy
    runs-on: ubuntu-24.04
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
