name: Linting and Formatting

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/envrc

      - uses: ./.github/actions/setup
        with:
          rust-components: rustfmt

      - name: Check formatting
        run: ./scripts/chores/lint.sh