name: Linting and Formatting

on:
  workflow_call:

jobs:
  lint:
    name: lint
    runs-on: ${{ vars.DEFAULT_RUNNER || 'ubuntu-24.04' }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: ./shell/.shock/actions/envrc

      - uses: ./.github/actions/setup
        with:
          rust-components: rustfmt

      - name: Check formatting
        run: ./shell/scripts/chores/lint.sh