name: Security Checks
on:
  workflow_call:

jobs:
  go:
    name: go
    runs-on: ${{ vars.DEFAULT_RUNNER || 'ubuntu-24.04' }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: ./shell/.shock/actions/envrc
      - uses: ./.github/actions/setup
        with:
          rust: false
      - name: Additional Tools
        run: ./shell/shock workspace govulncheck

      - name: Go Security
        run: cd go && govulncheck ./...

  rust:
    name: rust
    runs-on: ${{ vars.DEFAULT_RUNNER || 'ubuntu-24.04' }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: ./shell/.shock/actions/envrc
      - uses: ./.github/actions/setup
        with:
          go: false
      - name: Additional Tools
        run: ./shell/shock workspace cargo-audit

      - name: Rust Security
        run: cargo audit -f crates/Cargo.lock