name: Security Checks
on:
  workflow_call:

jobs:
  go:
    name: Go
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/envrc
      - uses: ./.github/actions/setup
        with:
          rust: false
      - name: Additional Tools
        run: ./scripts/chores/install_tools.sh govulncheck

      - name: Go Security
        run: cd go && govulncheck ./...

  rust:
    name: Rust
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/envrc
      - uses: ./.github/actions/setup
        with:
          go: false
      - name: Additional Tools
        run: ./scripts/chores/install_tools.sh cargo-audit

      - name: Rust Security
        run: cargo audit -f crates/Cargo.lock