name: Build and Publish Docs Site

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - site/**

jobs:
  deploy:
    name: deploy
    uses: ./.github/workflows/_deploy_docs.yaml
