name: Pull Request Hygiene
on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - assigned
      - unassigned

jobs:
  check-requirements:
    name: Check Requirements
    runs-on: ubuntu-24.04
    steps:
      - name: Check for assignee
        if: join(github.event.pull_request.assignees.*.login) == ''
        run: |
          echo "ERROR: PR must have at least one assignee"
          exit 1

      - name: Check for labels
        if: join(github.event.pull_request.labels.*.name, '') == ''
        run: |
          echo "ERROR: PR must have at least one label"
          exit 1

      - name: Check for description
        if: ${{ !github.event.pull_request.body }}
        run: |
          echo "ERROR: PR must have a description"
          exit 1