name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    uses: ./.github/workflows/_validate.yaml
    secrets: inherit

  test-install:
    uses: ./.github/workflows/_test_install.yaml
    with:
      mode: simulated
    secrets: inherit